# Generated by Django 5.1.6 on 2025-09-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelloposti',
            name='posto22',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
